--------------------------------------------------------------------------------
-- Copyright (c) 1995-2013 Xilinx, Inc.  All rights reserved.
--------------------------------------------------------------------------------
--   ____  ____ 
--  /   /\/   / 
-- /___/  \  /    Vendor: Xilinx 
-- \   \   \/     Version : 14.7
--  \   \         Application : xaw2vhdl
--  /   /         Filename : cdm_int_ext.vhd
-- /___/   /\     Timestamp : 02/06/2024 17:22:12
-- \   \  /  \ 
--  \___\/\___\ 
--
--Command: xaw2vhdl-st C:\Users\Docencia\Downloads\diseno_sincrono\diseno_sincrono\para proyecto\RAM\ipcore_dir\.\cdm_int_ext.xaw C:\Users\Docencia\Downloads\diseno_sincrono\diseno_sincrono\para proyecto\RAM\ipcore_dir\.\cdm_int_ext
--Design Name: cdm_int_ext
--Device: xc3s500e-5fg320
--
-- Module cdm_int_ext
-- Generated by Xilinx Architecture Wizard
-- Written for synthesis tool: XST

library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;
library UNISIM;
use UNISIM.Vcomponents.ALL;

entity cdm_int_ext is
   port ( U1_CLKFB_IN        : in    std_logic; 
          U1_CLKIN_IN        : in    std_logic; 
          U1_RST_IN          : in    std_logic; 
          U2_RST_IN          : in    std_logic; 
          U1_CLKDV_OUT       : out   std_logic; 
          U1_CLKIN_IBUFG_OUT : out   std_logic; 
          U1_CLK0_OUT        : out   std_logic; 
          U1_LOCKED_OUT      : out   std_logic; 
          U2_CLK0_OUT        : out   std_logic; 
          U2_LOCKED_OUT      : out   std_logic);
end cdm_int_ext;

architecture BEHAVIORAL of cdm_int_ext is
   signal GND_BIT            : std_logic;
   signal U1_CLKDV_BUF       : std_logic;
   signal U1_CLKFB_IBUFG     : std_logic;
   signal U1_CLKIN_IBUFG     : std_logic;
   signal U1_CLK0_OBUF       : std_logic;
   signal U2_CLKFB_IN        : std_logic;
   signal U2_CLK0_BUF        : std_logic;
begin
   GND_BIT <= '0';
   U1_CLKIN_IBUFG_OUT <= U1_CLKIN_IBUFG;
   U2_CLK0_OUT <= U2_CLKFB_IN;
   DCM_SP_INST1 : DCM_SP
   generic map( CLK_FEEDBACK => "1X",
            CLKDV_DIVIDE => 2.0,
            CLKFX_DIVIDE => 1,
            CLKFX_MULTIPLY => 4,
            CLKIN_DIVIDE_BY_2 => FALSE,
            CLKIN_PERIOD => 20.000,
            CLKOUT_PHASE_SHIFT => "NONE",
            DESKEW_ADJUST => "SYSTEM_SYNCHRONOUS",
            DFS_FREQUENCY_MODE => "LOW",
            DLL_FREQUENCY_MODE => "LOW",
            DUTY_CYCLE_CORRECTION => TRUE,
            FACTORY_JF => x"C080",
            PHASE_SHIFT => 0,
            STARTUP_WAIT => FALSE)
      port map (CLKFB=>U1_CLKFB_IBUFG,
                CLKIN=>U1_CLKIN_IBUFG,
                DSSEN=>GND_BIT,
                PSCLK=>GND_BIT,
                PSEN=>GND_BIT,
                PSINCDEC=>GND_BIT,
                RST=>U1_RST_IN,
                CLKDV=>U1_CLKDV_BUF,
                CLKFX=>open,
                CLKFX180=>open,
                CLK0=>U1_CLK0_OBUF,
                CLK2X=>open,
                CLK2X180=>open,
                CLK90=>open,
                CLK180=>open,
                CLK270=>open,
                LOCKED=>U1_LOCKED_OUT,
                PSDONE=>open,
                STATUS=>open);
   
   DCM_SP_INST2 : DCM_SP
   generic map( CLK_FEEDBACK => "1X",
            CLKDV_DIVIDE => 2.0,
            CLKFX_DIVIDE => 1,
            CLKFX_MULTIPLY => 4,
            CLKIN_DIVIDE_BY_2 => FALSE,
            CLKIN_PERIOD => 20.000,
            CLKOUT_PHASE_SHIFT => "NONE",
            DESKEW_ADJUST => "SYSTEM_SYNCHRONOUS",
            DFS_FREQUENCY_MODE => "LOW",
            DLL_FREQUENCY_MODE => "LOW",
            DUTY_CYCLE_CORRECTION => TRUE,
            FACTORY_JF => x"C080",
            PHASE_SHIFT => 0,
            STARTUP_WAIT => FALSE)
      port map (CLKFB=>U2_CLKFB_IN,
                CLKIN=>U1_CLKIN_IBUFG,
                DSSEN=>GND_BIT,
                PSCLK=>GND_BIT,
                PSEN=>GND_BIT,
                PSINCDEC=>GND_BIT,
                RST=>U2_RST_IN,
                CLKDV=>open,
                CLKFX=>open,
                CLKFX180=>open,
                CLK0=>U2_CLK0_BUF,
                CLK2X=>open,
                CLK2X180=>open,
                CLK90=>open,
                CLK180=>open,
                CLK270=>open,
                LOCKED=>U2_LOCKED_OUT,
                PSDONE=>open,
                STATUS=>open);
   
   U1_CLKDV_BUFG_INST : BUFG
      port map (I=>U1_CLKDV_BUF,
                O=>U1_CLKDV_OUT);
   
   U1_CLKFB_IBUFG_INST : IBUFG
      port map (I=>U1_CLKFB_IN,
                O=>U1_CLKFB_IBUFG);
   
   U1_CLKIN_IBUFG_INST : IBUFG
      port map (I=>U1_CLKIN_IN,
                O=>U1_CLKIN_IBUFG);
   
   U1_CLK0_OBUF_INST : OBUF
      port map (I=>U1_CLK0_OBUF,
                O=>U1_CLK0_OUT);
   
   U2_CLK0_BUFG_INST : BUFG
      port map (I=>U2_CLK0_BUF,
                O=>U2_CLKFB_IN);
   
end BEHAVIORAL;


